/**
 * This class is generated by jOOQ
 */
package com.hellokoding.jooq.model.dbo;


import com.hellokoding.jooq.model.DefaultCatalog;
import com.hellokoding.jooq.model.dbo.tables.Author;
import com.hellokoding.jooq.model.dbo.tables.Sysdiagrams;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dbo extends SchemaImpl {

    private static final long serialVersionUID = -1046945164;

    /**
     * The reference instance of <code>dbo</code>
     */
    public static final Dbo DBO = new Dbo();

    /**
     * The table <code>dbo.author</code>.
     */
    public final Author AUTHOR = com.hellokoding.jooq.model.dbo.tables.Author.AUTHOR;

    /**
     * The table <code>dbo.sysdiagrams</code>.
     */
    public final Sysdiagrams SYSDIAGRAMS = com.hellokoding.jooq.model.dbo.tables.Sysdiagrams.SYSDIAGRAMS;

    /**
     * No further instances allowed
     */
    private Dbo() {
        super("dbo", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Sysdiagrams.SYSDIAGRAMS);
    }
}
