/**
 * This class is generated by jOOQ
 */
package com.hellokoding.jooq.model.dbo;


import com.hellokoding.jooq.model.dbo.tables.Author;
import com.hellokoding.jooq.model.dbo.tables.Sysdiagrams;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in dbo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>dbo.author</code>.
     */
    public static final Author AUTHOR = com.hellokoding.jooq.model.dbo.tables.Author.AUTHOR;

    /**
     * The table <code>dbo.sysdiagrams</code>.
     */
    public static final Sysdiagrams SYSDIAGRAMS = com.hellokoding.jooq.model.dbo.tables.Sysdiagrams.SYSDIAGRAMS;
}
